apiVersion: v1
kind: Service
metadata:
  name: appropriate-nc
  labels:
    app: tcp-client
spec:
  ports:
    - port: 9999
  selector:
    app: tcp-client
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-client
  labels:
    app: tcp-client
spec:
  selector:
    matchLabels:
      app: tcp-client
  template:
    metadata:
      labels:
        app: tcp-client
    spec:
      containers:
        - image: appropriate/nc
          name: appropriate-nc
          ports:
            - containerPort: 9999
          command:
            - sh
            - -c
            - "exec tail -f /dev/null"
