#
# You'll need to create a config map before creating this SparkApplication
#
# kubectl create configmap flight-stateful-conf --from-file=configMap/
#
---
apiVersion: "sparkoperator.k8s.io/v1beta1"
kind: SparkApplication
metadata:
  name: flight-stateful
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "david62243/apache-spark-testing:0.1"
  imagePullPolicy: Always
  mainClass: com.esri.realtime.stream.FlightLastKnownPositionKeeper
  mainApplicationFile: "local:///opt/spark/apache-spark-testing-assembly-0.1.jar"
  arguments:
    - gateway-cp-kafka:9092
    - flight-stateful
  sparkVersion: "2.4.0"
  sparkConfigMap: spark-conf
  sparkConf:
    "spark.executor.extraJavaOptions": "-Dlog4j.configurationFile=/opt/spark/log4j2conf.xml"
    "spark.driver.extraJavaOptions": "-Dlog4j.configurationFile=/opt/spark/log4j2conf.xml"
  restartPolicy:
    type: Always 
  driver:
    cores: 0.1
    coreLimit: "200m"
    memory: "512m"
    labels:
      version: 2.4.0
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.0
