---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rttest-send-deployment
spec:
  selector:
    matchLabels:
      app: rttest-send
  replicas: 1
  template:
    metadata:
      labels:
        app: rttest-send
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values:
                - agent
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: rttest-send
        image: david62243/rttest-send:v0.1
        command:
          - sh
          - -c
          - "exec tail -f /dev/null"
        imagePullPolicy: Always
