---
apiVersion: "sparkoperator.k8s.io/v1beta1"
kind: SparkApplication
metadata:
  name: word-count-stateful-network
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "david62243/apache-spark-testing:0.1"
  imagePullPolicy: Always
  mainClass: com.esri.realtime.stream.StreamingApp
  Arguments: 
  mainApplicationFile: "local:///opt/spark/apache-spark-testing_2.11-0.1.jar"
  sparkVersion: "2.4.0"
  sparkConfigMap: word-count-sparkop-conf
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 0.1
    coreLimit: "200m"
    memory: "512m"
    labels:
      version: 2.4.0
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.0
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
